# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate data
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - run: node generate.js
    - name: Commit & Push Generated Data
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Actions Auto Build"
        git add -f .
        git commit -m "docs: generate documents" || true
        git push --force origin HEAD:refs/heads/main
